### ISSUE TITLE
Please provide version v4.1.3

### ISSUE THREAD

**Issue by mkurz** [webjars/less#20]
https://github.com/less/less.js/releases/tag/v4.1.3

Thanks James!

**Comment by jamesward** [comment]
This will be released shortly.

**Comment by mkurz** [comment]
@jamesward I can see this was published here: https://repo1.maven.org/maven2/org/webjars/less/

However I thought this will be published here https://repo1.maven.org/maven2/org/webjars/less-node/ ?

How does that less-node package work? I can not see a GitHub repo for it...

When I search for less-node at https://www.webjars.org/ and click on "LESS Node" it takes me to this repo here.

![image](https://github.com/webjars/less/assets/644927/a3101d0c-b8f8-48f0-8ba8-c676b09588a0)

**Comment by jamesward** [comment]
We used to publish different WebJars for web & node but changed that to just a single WebJar:
https://github.com/webjars/less/commit/b2b6d528f3a8a3353960a3c521fa775e692090c9

I think we did that because maybe the upstream project doesn't have different artifacts for each anymore?  I can't quite remember.  Or maybe the NPM WebJar for Less covers the Node artifact?

**Comment by mkurz** [comment]
Thanks, I will give the other webjar a try.
